import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; 
import QueryProvider from "@/queryProvider/QueryProvider";
import NavBar from "@/page&component/NavBar/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <NavBar></NavBar>
          <div className="container my-20 mx-auto px-4 md:px-9  min-h-[calc(100vh-380px)]"> 
          {children}
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
